
const SB='https://ovaqwpzffawtozgidbav.supabase.co',KEY='sb_publishable_WJNbTVKF66c6Y7AVfxaYBA_7gpkEUyP';let S={people:[],shifts:[],tasks:[],notes:[]},FAQ=[],tab=new URLSearchParams(location.search).get('tab')==='chat'?'chat':'calendar',admin=false,adminPass='',personFilter='전체',typeFilter='전체',faqProduct='전체',faqQuery='',openFaq=new Set(),staff=null,staffToken=localStorage.getItem('bixpo_staff_token')||'',CHAT=[],chatPushRegistered=false,chatNotified=new Set(),chatImageUrls=new Map(),chatImageSigning=false,chatSelectedImage=null,chatSelectedImageUrl='',chatSending=false;const T=[['calendar','📅 통합 달력'],['people','👥 개인별 일정'],['shifts','🪪 근무표'],['tasks','☑ 준비·시연'],['faq','💬 전시 FAQ'],['chat','💬 T/F 채팅'],['adminpanel','⚙️ 관리자']];
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function md(s){let m=String(s||'').match(/11\/(\d{1,2})/);return m?+m[1]:null}
function stayRange(s){let a=[...String(s||'').matchAll(/11\/(\d{1,2})/g)].map(x=>+x[1]);return a.length>1?[a[0],a[1]]:null}
function selected(name){return personFilter==='전체'||String(name||'').replaceAll(' ','').split(',').includes(personFilter)}
function typed(t){return typeFilter==='전체'||typeFilter===t||(typeFilter==='travel'&&(t==='depart'||t==='return'))}
function events(d){let a=[];S.people.forEach(p=>{if(!selected(p.name))return;if(typed('depart')&&md(p.down)===d)a.push(['depart','↓ '+p.name+' 출발 · '+p.down]);if(typed('return')&&md(p.up)===d)a.push(['return','↑ '+p.name+' 복귀 · '+p.up]);let r=stayRange(p.stay);if(typed('stay')&&r&&d>=r[0]&&d<r[1])a.push(['stay','⌂ '+p.name+' 숙박'])});S.shifts.forEach(s=>{let names=String(s.people||'').replaceAll(' ','').split(',');if(typed('shift')&&md(s.date)===d&&(personFilter==='전체'||names.includes(personFilter)))a.push(['shift','● '+s.period+' '+s.time+' · '+s.people])});if(typed('prep')&&d===3&&(personFilter==='전체'||['최재혁','정승훈'].includes(personFilter)))a.push(['prep','◆ 부스 준비 · 최재혁, 정승훈']);if(typed('prep')&&d===6&&(personFilter==='전체'||['최재혁','신소망'].includes(personFilter)))a.push(['prep','◆ 부스 철거 · 최재혁, 신소망']);return a}
function calendar(){let h='<div class="card"><div class="row between"><h3>2026년 11월 1주차</h3><span class="muted">11월 2일(월) ~ 6일(금)</span></div><div class="filter"><b>내 일정 보기</b><select onchange="personFilter=this.value;render()"><option>전체</option>'+S.people.map(p=>'<option '+(personFilter===p.name?'selected':'')+'>'+esc(p.name)+'</option>').join('')+'</select><b>일정 종류</b><select onchange="typeFilter=this.value;render()"><option value="전체">전체</option><option value="travel" '+(typeFilter==='travel'?'selected':'')+'>출발·복귀</option><option value="stay" '+(typeFilter==='stay'?'selected':'')+'>숙박</option><option value="shift" '+(typeFilter==='shift'?'selected':'')+'>전시근무</option><option value="prep" '+(typeFilter==='prep'?'selected':'')+'>부스준비</option></select><span class="muted">이름과 일정 종류를 함께 선택할 수 있습니다.</span></div><div class="legend"><span class="depart">↓ 출발</span><span class="stay">⌂ 숙박</span><span class="shift">● 전시근무</span><span class="prep">◆ 부스준비</span><span class="return">↑ 복귀</span></div><div class="cal">'+['2 월','3 화','4 수','5 목','6 금'].map((x,i)=>{let d=i+2,es=events(d),order=['depart','stay','shift','prep','return'];es.sort((a,b)=>order.indexOf(a[0])-order.indexOf(b[0]));return '<div class="day '+(es.length?'eventday':'')+'"><div class="num">'+x+'</div>'+order.map(type=>{let rows=es.filter(e=>e[0]===type);return rows.length?'<div class="daygroup '+type+'">'+rows.map(e=>'<div class="ev '+type+'">'+esc(e[1])+'</div>').join('')+'</div>':''}).join('')+'</div>'}).join('')+'</div></div>';return h}
function toggleHotel(){let el=document.getElementById('hotelCard');if(!el)return;let collapsed=el.classList.toggle('collapsed');localStorage.setItem('bixpo_hotel_collapsed',collapsed?'1':'0');let a=document.getElementById('hotelArrow');if(a)a.textContent=collapsed?'▼':'▲'}
function renderHotel(){let h=S.hotel;if(!h){document.querySelector('#hotelArea').innerHTML='';return}let stays=S.people.filter(p=>stayRange(p.stay)).map(p=>'<div><b>'+esc(p.name)+'</b> · '+esc(p.stay)+'</div>').join(''),collapsed=localStorage.getItem('bixpo_hotel_collapsed')==='1';document.querySelector('#hotelArea').innerHTML='<div id="hotelCard" class="hotel '+(collapsed?'collapsed':'')+'"><div class="row between hotelhead" onclick="toggleHotel()"><div><h3>🏨 숙소정보</h3><b>'+esc(h.name)+'</b> <span class="badge">'+esc(h.status||'')+'</span></div><span id="hotelArrow" class="hotelarrow">'+(collapsed?'▼':'▲')+'</span></div><div class="hotelbody"><div class="muted">'+esc(h.note||'')+'</div><a class="hotelbtn" href="'+esc(h.booking_url||'#')+'" target="_blank" rel="noopener" onclick="event.stopPropagation()">숙소 상세보기</a><div style="margin-top:10px">'+stays+'</div></div></div>'}
function renderNotice(){let ns=S.notes||[],h='';if(ns.length)h='<div class="notice-list">'+ns.map((n,i)=>'<div class="notice-row"><h3>📢 '+esc(n.title||'공지사항')+'</h3><p>'+esc(n.text||'')+'</p><div class="notice-meta">'+esc(n.date||'')+'</div>'+(admin?'<div class="notice-actions row"><button class="edit" onclick="editNotice('+i+')">수정</button><button class="edit" onclick="deleteNotice('+i+')">삭제</button></div>':'')+'</div>').join('')+'</div>';if(admin)h+='<div class="notice-actions"><button class="admin" onclick="addNotice()">+ 공지사항 등록</button></div>';document.querySelector('#noticeArea').innerHTML=h}
function announceNotice(n){try{let seen=JSON.parse(localStorage.getItem('bixpo_seen_notices')||'[]');if(seen.includes(n.id))return;localStorage.setItem('bixpo_seen_notices',JSON.stringify([...seen,n.id].slice(-50)));if('Notification'in window&&Notification.permission==='granted')new Notification(n.title||'BIXPO T/F 새 공지',{body:n.text||''});let A=window.AudioContext||window.webkitAudioContext;if(A){let ac=new A(),o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);o.frequency.value=880;g.gain.setValueAtTime(.12,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.45);o.start();o.stop(ac.currentTime+.45)}}catch(e){}}
function checkNewNotices(before){let old=new Set((before||[]).map(n=>n.id));(S.notes||[]).forEach(n=>{if(!old.has(n.id))announceNotice(n)})}
async function addNotice(){let title=prompt('공지 제목','공지사항');if(title===null)return;let text=prompt('공지 내용을 입력하세요.','');if(text===null||!text.trim())return;if(!S.notes)S.notes=[];let n={id:'notice-'+Date.now(),title:title||'공지사항',text,date:new Date().toLocaleString('ko-KR')};S.notes.unshift(n);let ok=await persist();if(ok){announceNotice(n);try{let r=await pushApi({action:'notify',password:adminPass,title:'안산지사 BIXPO 성공기원 T/F · '+n.title,body:n.text});if(r.sent!==undefined)alert('푸시 알림을 '+r.sent+'대 기기에 발송했습니다.')}catch(e){alert(e.kind==='auth'?'공지는 저장됐지만 푸시 인증에 실패했습니다.':'공지는 저장됐지만 푸시 발송에 실패했습니다.')}}}
function editNotice(i){let n=S.notes[i],title=prompt('공지 제목',n.title||'공지사항');if(title===null)return;let text=prompt('공지 내용',n.text||'');if(text===null)return;if(!text.trim())return;Object.assign(n,{title:title||'공지사항',text,date:new Date().toLocaleString('ko-KR')});persist()}
function deleteNotice(i){if(!confirm('이 공지사항을 삭제할까요?'))return;S.notes.splice(i,1);persist()}
async function staffApi(body){let r=await fetch(SB+'/functions/v1/bixpo-staff',{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify(body)}),j={};try{j=await r.json()}catch(_){}if(!r.ok)throw new Error(j.error||'staff');return j}
async function restoreStaff(){if(!staffToken)return;try{let j=await staffApi({action:'me',token:staffToken});staff={name:j.name,role:j.role};applyStaff()}catch(e){localStorage.removeItem('bixpo_staff_token');staffToken=''}}
function applyStaff(){if(!staff)return;staffBtn.textContent='👤 '+staff.name+(staff.role==='admin'?' · 관리자':'');personFilter=staff.name;if(staff.role==='admin'){admin=true;adminBtn.style.display='none'}if(staffToken)syncStaffPushSubscription();render()}
async function staffLogin(){if(staff){try{await staffApi({action:'logout',token:staffToken})}catch(_){}staff=null;staffToken='';localStorage.removeItem('bixpo_staff_token');admin=false;adminBtn.style.display='';staffBtn.textContent='👤 직원 로그인';personFilter='전체';render();return}let box=document.createElement('div');box.id='staffLoginModal';box.style.cssText='position:fixed;inset:0;background:#0008;z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px';box.innerHTML='<div style="background:white;border-radius:16px;padding:20px;width:min(420px,100%)"><h3 style="margin-top:0">👤 직원 로그인</h3><label>이름 선택<select id="staffNameSelect" style="width:100%;padding:11px;margin:7px 0 12px;border:1px solid #ddd;border-radius:9px"><option value="">본인 이름을 선택하세요</option>'+S.people.map(p=>'<option value="'+esc(p.name)+'">'+esc(p.name)+(p.name==='최재혁'?' · 관리자':'')+'</option>').join('')+'</select></label><label>PIN 4자리<input id="staffPinInput" type="password" inputmode="numeric" maxlength="4" pattern="[0-9]*" placeholder="••••" style="width:100%;padding:11px;margin:7px 0 15px;border:1px solid #ddd;border-radius:9px;font-size:20px;letter-spacing:6px"></label><div class="row" style="justify-content:flex-end"><button class="edit" onclick="document.getElementById(\'staffLoginModal\').remove()">취소</button><button class="admin" id="staffLoginGo">로그인</button></div></div>';document.body.appendChild(box);document.getElementById('staffLoginGo').onclick=async()=>{let name=document.getElementById('staffNameSelect').value,pin=document.getElementById('staffPinInput').value;if(!name){alert('본인 이름을 선택해 주세요.');return}if(!/^\d{4}$/.test(pin)){alert('PIN 숫자 4자리를 입력해 주세요.');return}try{let j=await staffApi({action:'login',name,pin});box.remove();staffToken=j.token;localStorage.setItem('bixpo_staff_token',staffToken);staff={name:j.name,role:j.role};applyStaff()}catch(e){alert(e.message==='pin_not_set'?'아직 PIN이 설정되지 않았습니다. 관리자에게 문의하세요.':'이름 또는 PIN이 맞지 않습니다.')}}}
function chatMessageParts(message){
 const raw=String(message||'');
 const match=raw.match(/\n?\[\[bixpo-image:(chat\/[^\r\n\]]+)\]\]$/);
 const path=match?.[1]||'';
 if(path&&!/^chat\/[^/]{1,180}\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(?:jpg|png|webp)$/i.test(path))return {text:raw.trim(),imagePath:''};
 return path?{text:raw.slice(0,match.index).trim(),imagePath:path}:{text:raw.trim(),imagePath:''}
}
function chatNotificationBody(m){let p=chatMessageParts(m?.message);return p.imagePath?(p.text?p.text+' · 📷 사진':'📷 사진'):p.text}
function chatMessageMarkup(m){
 let p=chatMessageParts(m.message),photo='',text=p.text?'<div class="chat-message-text">'+esc(p.text)+'</div>':'';
 if(p.imagePath){let saved=chatImageUrls.get(p.imagePath);photo=saved?.url?'<a class="chat-image-link" href="'+esc(saved.url)+'" target="_blank" rel="noopener"><img src="'+esc(saved.url)+'" alt="채팅 첨부 사진" loading="lazy"></a>':'<div class="chat-image-wait">사진을 불러오는 중...</div>'}
 let id=String(m.id||'').replace(/\D/g,'');
 return '<div class="msg '+(m.staff_name===staff?.name?'me':'')+'"><div class="msghead"><b>'+esc(m.staff_name)+'</b> · '+new Date(m.created_at).toLocaleString('ko-KR')+(staff?.role==='admin'&&id?' <button class="edit" onclick="deleteChat('+id+')">삭제</button>':'')+'</div>'+text+photo+'</div>'
}
async function loadChatImageUrls(){
 if(!staffToken||tab!=='chat'||document.visibilityState!=='visible'||chatImageSigning)return;
 let now=Date.now(),paths=[...new Set(CHAT.map(m=>chatMessageParts(m.message).imagePath).filter(Boolean))].filter(path=>{let x=chatImageUrls.get(path);return !x||x.expiresAt<now+120000});
 if(!paths.length)return;
 chatImageSigning=true;
 try{
  for(let i=0;i<paths.length;i+=50){
   let batch=paths.slice(i,i+50),j=await pushApi({action:'chat_image_urls',token:staffToken,paths:batch});
   batch.forEach(path=>chatImageUrls.set(path,{url:'',expiresAt:Date.now()+60000}));
   (j.images||[]).forEach(x=>{if(x.path&&x.signedUrl){let url=String(x.signedUrl);if(!/^https?:\/\//i.test(url))url=new URL(url,SB+'/storage/v1/').href;chatImageUrls.set(x.path,{url,expiresAt:Date.now()+55*60*1000})}})
  }
 }catch(_){}
 finally{chatImageSigning=false}
 renderChatMessages()
}
async function loadChat(){if(!staffToken)return;try{let j=await staffApi({action:'chat_list',token:staffToken}),next=j.messages||[];let oldIds=new Set(CHAT.map(m=>m.id)),fresh=next.filter(m=>!oldIds.has(m.id)&&m.staff_name!==staff?.name);let changed=JSON.stringify(next)!==JSON.stringify(CHAT);CHAT=next;if(tab==='chat'&&changed)renderChatMessages();if(tab==='chat')loadChatImageUrls();if(oldIds.size&&fresh.length)fresh.forEach(m=>notifyChat(m))}catch(_){}}
function playChatSound(){try{let A=window.AudioContext||window.webkitAudioContext;if(A){let ac=new A(),o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);o.frequency.value=740;g.gain.setValueAtTime(.09,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.25);o.start();o.stop(ac.currentTime+.25)}}catch(e){}}
async function notifyChat(m){let id=String(m?.id??'');if(!id||chatNotified.has(id))return;chatNotified.add(id);if(chatNotified.size>250)chatNotified.delete(chatNotified.values().next().value);let title=(m.staff_name||'새 메시지')+' · 새 채팅',body=chatNotificationBody(m);if(document.visibilityState==='visible'){playChatSound();return}let pushActive=chatPushRegistered;if(!pushActive&&'serviceWorker'in navigator&&'PushManager'in window){try{let reg=await navigator.serviceWorker.ready;pushActive=chatPushRegistered=!!(await reg.pushManager.getSubscription())}catch(_){}}if(!pushActive&&'Notification'in window&&Notification.permission==='granted')try{new Notification(title,{body,icon:'/icon.svg',tag:'bixpo-chat-local-'+id})}catch(e){}}
function renderChatMessages(){let box=document.getElementById('chatbox');if(!box)return;let nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<80;box.innerHTML=CHAT.map(chatMessageMarkup).join('');if(nearBottom)box.scrollTop=box.scrollHeight}
function chatView(){if(!staff)return '<div class="card"><h3>💬 T/F 채팅</h3><p>직원별 PIN으로 로그인하면 팀 채팅을 사용할 수 있습니다.</p><button class="admin" onclick="staffLogin()">직원 로그인</button></div>';return '<div class="card"><div class="row between"><div><h3>💬 T/F 채팅</h3><div class="muted">'+esc(staff.name)+' 이름으로 메시지가 등록됩니다.</div></div></div><div class="chatbox" id="chatbox">'+CHAT.map(chatMessageMarkup).join('')+'</div><div class="chatinput"><button class="edit chat-attach" type="button" onclick="chooseChatImage()" aria-label="사진 첨부">📷</button><input id="chatText" maxlength="1000" placeholder="메시지 입력 · 사진만 보내도 됩니다" onkeydown="chatKeydown(event)"><input id="chatImageInput" type="file" accept="image/*" hidden onchange="selectChatImage(this)"><button class="admin chat-send-btn" onclick="sendChat()">전송</button></div><div id="chatImagePreview" class="chat-image-preview"></div></div>'}
function chatKeydown(e){if(e.key==='Enter')sendChat()}
function chooseChatImage(){if(!chatSending)document.getElementById('chatImageInput')?.click()}
async function compressChatImage(file){
 const objectUrl=URL.createObjectURL(file);let image;
 try{image=await new Promise((resolve,reject)=>{let el=new Image();el.onload=()=>resolve(el);el.onerror=()=>reject(new Error('image_decode'));el.src=objectUrl})}
 finally{URL.revokeObjectURL(objectUrl)}
 let w=image.naturalWidth||image.width,h=image.naturalHeight||image.height;if(!w||!h)throw new Error('image_decode');
 for(let maxSide of [1600,1400,1200]){
  let scale=Math.min(1,maxSide/Math.max(w,h)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(w*scale));canvas.height=Math.max(1,Math.round(h*scale));
  let context=canvas.getContext('2d');if(!context)throw new Error('canvas');
  context.drawImage(image,0,0,canvas.width,canvas.height);
  for(let quality of [.84,.76,.68,.6]){
   let blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));
   if(blob&&blob.size<=1800*1024)return blob
  }
 }
 throw new Error('image_too_large')
}
async function selectChatImage(input){
 if(chatSending)return;
 let file=input?.files?.[0];if(input)input.value='';if(!file)return;
 if(!String(file.type||'').startsWith('image/')){alert('사진 파일을 선택해 주세요.');return}
 if(file.size>25*1024*1024){alert('원본 사진은 25MB 이하로 선택해 주세요.');return}
 try{let blob=await compressChatImage(file);if(chatSelectedImageUrl)URL.revokeObjectURL(chatSelectedImageUrl);chatSelectedImage=blob;chatSelectedImageUrl=URL.createObjectURL(blob);renderChatImagePreview()}catch(_){alert('사진을 읽거나 압축하지 못했습니다. JPG, PNG 또는 WebP 사진으로 다시 선택해 주세요.')}
}
function renderChatImagePreview(){
 let host=document.getElementById('chatImagePreview');if(!host)return;
 host.innerHTML=chatSelectedImage?'<div class="chat-image-preview-card"><img src="'+esc(chatSelectedImageUrl)+'" alt="첨부 사진 미리보기"><div class="chat-image-preview-info">첨부 사진 · '+(chatSelectedImage.size/1024).toFixed(0)+'KB</div><button class="edit" type="button" onclick="clearChatImage()">사진 취소</button></div>':''
}
function clearChatImage(){if(chatSelectedImageUrl)URL.revokeObjectURL(chatSelectedImageUrl);chatSelectedImage=null;chatSelectedImageUrl='';renderChatImagePreview()}
async function uploadChatImage(blob){
 let form=new FormData();form.append('action','chat_upload');form.append('token',staffToken);form.append('image',blob,'chat-image.jpg');
 let r;try{r=await fetch(SB+'/functions/v1/bixpo-push',{method:'POST',headers:{apikey:KEY},body:form})}catch(e){let x=new Error('network');x.kind='network';throw x}
 let j={};try{j=await r.json()}catch(_){}
 if(!r.ok){let x=new Error(j.error||'upload');x.kind='upload';x.status=r.status;throw x}
 return j.path
}
async function sendChat(){
 if(chatSending)return;
 let e=document.getElementById('chatText'),message=e?.value.trim()||'',image=chatSelectedImage;
 if(!message&&!image)return;
 chatSending=true;let sendButton=document.querySelector('.chat-send-btn'),attachButton=document.querySelector('.chat-attach');if(sendButton)sendButton.disabled=true;if(attachButton)attachButton.disabled=true;
 let senderEndpoint='';
 try{
  if('serviceWorker'in navigator&&'PushManager'in window)try{let reg=await navigator.serviceWorker.ready,sub=await reg.pushManager.getSubscription();senderEndpoint=sub?.endpoint||''}catch(_){}
  let imagePath=image?await uploadChatImage(image):'';
  await pushApi({action:'chat_send',token:staffToken,message,imagePath,senderEndpoint});
  if(e)e.value='';if(image)clearChatImage();await loadChat();e=document.getElementById('chatText');if(e)e.focus()
 }catch(err){alert(err.kind==='upload'?'사진 전송에 실패했습니다. 사진 크기나 인터넷 연결을 확인해 주세요.':'메시지 전송에 실패했습니다.')}
 finally{chatSending=false;sendButton=document.querySelector('.chat-send-btn');attachButton=document.querySelector('.chat-attach');if(sendButton)sendButton.disabled=false;if(attachButton)attachButton.disabled=false}
}
async function deleteChat(id){if(!confirm('이 메시지를 삭제할까요?'))return;let message=CHAT.find(m=>String(m.id)===String(id))?.message||'',imagePath=chatMessageParts(message).imagePath;try{await staffApi({action:'chat_delete',token:staffToken,id});if(imagePath)try{await pushApi({action:'chat_image_delete',token:staffToken,path:imagePath})}catch(_){console.warn('채팅 사진 정리 실패',imagePath)}await loadChat()}catch(_){alert('삭제할 수 없습니다.')}}
async function adminSetPin(name){let pin=prompt(name+'의 새 PIN 4자리를 입력하세요.');if(!pin)return;if(!/^\d{4}$/.test(pin)){alert('PIN은 숫자 4자리로 입력해 주세요.');return}try{await staffApi({action:'set_pin',token:staffToken,name,pin});alert(name+' PIN을 설정했습니다. 기존 로그인 세션은 해제됩니다.')}catch(_){alert('PIN 설정에 실패했습니다.')}}
function adminPanel(){if(!admin)return '<div class="card"><h3>⚙️ 관리자</h3><p>관리자 로그인이 필요합니다.</p></div>';let rows=S.people.map(p=>'<div class="item row between"><div><b>'+esc(p.name)+'</b>'+(p.name==='최재혁'?' <span class="badge">관리자</span>':' <span class="muted">직원</span>')+'</div><div class="row"><button class="edit" onclick="setPinFromAdmin(\''+esc(p.name)+'\')">PIN 설정/재설정</button><button class="edit" onclick="revokeFromAdmin(\''+esc(p.name)+'\')">강제 로그아웃</button></div></div>').join('');return '<div class="card"><h3>⚙️ 관리자 화면</h3><div class="muted">직원 로그인과 권한을 관리합니다. 최재혁은 직원 PIN 로그인 시 관리자 권한이 활성화됩니다.</div>'+rows+'</div><div class="card"><h3>관리 기능</h3><div class="item">📅 일정·숙박·근무표 — 각 메뉴에서 수정</div><div class="item">☑ 준비·시연 — 추가·수정·삭제</div><div class="item">📢 공지사항 — 등록·수정·삭제 및 Push 발송</div><div class="item">💬 전시 FAQ — 추가·수정·삭제</div><div class="item">💬 T/F 채팅 — 최재혁 관리자 로그인 시 전체 메시지 관리</div></div>'}
async function adminStaffApi(action,name,pin){let r=await fetch(SB+'/functions/v1/bixpo-admin',{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({action,password:adminPass,name,pin})});let j={};try{j=await r.json()}catch(_){}if(!r.ok)throw new Error(j.error||'admin');return j}
async function setPinFromAdmin(name){let pin=prompt(name+'의 새 PIN 4자리를 입력하세요.');if(!pin)return;if(!/^\d{4}$/.test(pin)){alert('PIN은 숫자 4자리로 입력해 주세요.');return}try{await adminStaffApi('set_staff_pin',name,pin);alert(name+'의 PIN을 설정했습니다. 기존 직원 로그인 세션은 해제됩니다.')}catch(e){alert('PIN 설정에 실패했습니다.')}}
async function revokeFromAdmin(name){if(!confirm(name+'의 로그인된 모든 기기를 로그아웃할까요?'))return;try{await adminStaffApi('revoke_staff',name);alert(name+'의 기존 로그인 세션을 해제했습니다.')}catch(e){alert('강제 로그아웃에 실패했습니다.')}}

async function loadFAQ(){try{let r=await fetch(SB+'/rest/v1/bixpo_faq?select=*&order=sort_order.asc',{headers:{apikey:KEY,Authorization:'Bearer '+KEY},cache:'no-store'});if(r.ok)FAQ=await r.json()}catch(e){}if(tab==='faq')render()}
function faqMatch(x){let q=faqQuery.trim().toLowerCase();return (faqProduct==='전체'||x.product===faqProduct)&&(!q||[x.question,x.short_answer,x.detail,x.category,x.product].join(' ').toLowerCase().includes(q))}
function faqView(){let list=FAQ.filter(faqMatch);return '<div class="card"><div class="row between"><div><h3>💬 BIXPO 전시 FAQ</h3><div class="muted">관람객 질문의 핵심어를 검색하세요 · <span id="faqCount">'+list.length+'</span>개 결과</div></div>'+(admin?'<button class="admin" onclick="addFAQ()">+ FAQ 추가</button>':'')+'</div><input id="faqSearch" class="faq-search" placeholder="예: 사고사진, AI, 서명, 영상, 케이블…" value="'+esc(faqQuery)+'" oninput="filterFAQInPlace(this.value)"><div class="faqfilters">'+['전체','Power TBM','Safety 4-Cut','공통'].map(x=>'<button class="'+(faqProduct===x?'on':'')+'" onclick="faqProduct=\''+x+'\';render()">'+x+'</button>').join('')+'</div>'+list.map((x,i)=>'<div class="faqitem '+(openFaq.has(x.id)?'open':'')+'" id="faq'+x.id+'" data-faq-id="'+x.id+'"><div class="faq-q" onclick="toggleFAQ('+x.id+')"><span class="producttag">'+esc(x.product)+'</span><span class="producttag">'+esc(x.category)+'</span> '+esc(x.question)+'</div><div class="faq-a"><div class="faq-short">'+esc(x.short_answer)+'</div><div class="faq-detail">'+esc(x.detail)+'</div>'+(admin?'<div class="row" style="margin-top:10px"><button class="edit" onclick="event.stopPropagation();editFAQ('+x.id+')">수정</button><button class="edit" onclick="event.stopPropagation();deleteFAQ('+x.id+')">삭제</button></div>':'')+'</div></div>').join('')+'</div>'}
function toggleFAQ(id){if(openFaq.has(id))openFaq.delete(id);else openFaq.add(id);let el=document.getElementById('faq'+id);if(el)el.classList.toggle('open',openFaq.has(id))}
function filterFAQInPlace(v){faqQuery=v;let q=v.trim().toLowerCase(),count=0;document.querySelectorAll('.faqitem').forEach(el=>{let x=FAQ.find(f=>String(f.id)===String(el.dataset.faqId));let ok=x&&(faqProduct==='전체'||x.product===faqProduct)&&(!q||[x.question,x.short_answer,x.detail,x.category,x.product].join(' ').toLowerCase().includes(q));el.style.display=ok?'':'none';if(ok)count++});let n=document.getElementById('faqCount');if(n)n.textContent=count}
async function faqAdmin(action,payload){let r=await fetch(SB+'/functions/v1/bixpo-faq-admin',{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({action,password:adminPass,...payload})});if(r.status===401)throw new Error('auth');if(!r.ok)throw new Error('save')}
async function addFAQ(){let product=prompt('제품 구분: Power TBM / Safety 4-Cut / 공통','Power TBM');if(!product)return;let category=prompt('분류','현장질문');if(!category)return;let question=prompt('질문');if(!question)return;let short_answer=prompt('10초 답변');if(!short_answer)return;let detail=prompt('자세한 설명','')??'';try{await faqAdmin('add',{item:{product,category,question,short_answer,detail}});await loadFAQ();alert('FAQ를 추가했습니다.')}catch(e){alert(e.message==='auth'?'관리자 인증 오류입니다.':'FAQ 저장에 실패했습니다.')}}
async function editFAQ(id){let x=FAQ.find(v=>v.id===id);if(!x)return;let product=prompt('제품 구분',x.product);if(product===null)return;let category=prompt('분류',x.category);if(category===null)return;let question=prompt('질문',x.question);if(question===null)return;let short_answer=prompt('10초 답변',x.short_answer);if(short_answer===null)return;let detail=prompt('자세한 설명',x.detail||'');if(detail===null)return;try{await faqAdmin('update',{item:{...x,product,category,question,short_answer,detail}});await loadFAQ();alert('FAQ를 수정했습니다.')}catch(e){alert('FAQ 수정에 실패했습니다.')}}
async function deleteFAQ(id){if(!confirm('이 FAQ를 삭제할까요?'))return;try{await faqAdmin('delete',{id});await loadFAQ()}catch(e){alert('FAQ 삭제에 실패했습니다.')}}
function visibleTabs(){return admin?T:T.filter(x=>!['adminpanel','people','shifts'].includes(x[0]))}
function renderTabs(){document.querySelector('#tabs').innerHTML=visibleTabs().map(x=>'<button class="'+(tab===x[0]?'on':'')+'" onclick="tab=\''+x[0]+'\';render()">'+x[1]+'</button>').join('')}
function render(){renderNotice();renderHotel();if(!admin&&['people','shifts','adminpanel'].includes(tab))tab='calendar';renderTabs();let h='';
if(tab==='calendar')h=calendar();
if(tab==='people')h='<div class="card"><div class="row between"><h3>개인별 출장 일정</h3>'+(admin?'<button class="admin" onclick="addPerson()">+ 인원 추가</button>':'')+'</div>'+S.people.map((p,i)=>'<div class="item"><div class="row between"><div><b>'+esc(p.name)+'</b> <span class="badge">'+esc(p.role)+'</span></div>'+(admin?'<button class="edit" onclick="editPerson('+i+')">수정</button>':'')+'</div><div>↓ '+esc(p.down)+'</div><div>⌂ '+esc(p.stay)+'</div><div>↑ '+esc(p.up)+'</div>'+(p.note?'<div class="muted">'+esc(p.note)+'</div>':'')+'</div>').join('')+'</div>';
if(tab==='shifts')h='<div class="card"><h3>전시안내 근무표</h3>'+S.shifts.map((s,i)=>'<div class="item row between"><div><b>'+esc(s.date)+' '+esc(s.period)+' '+esc(s.time)+'</b><div>'+esc(s.people)+'</div></div>'+(admin?'<button class="edit" onclick="editShift('+i+')">수정</button>':'')+'</div>').join('')+'</div>';
if(tab==='faq')h=faqView();
if(tab==='chat'){h=chatView();setTimeout(loadChatImageUrls,0)}
if(tab==='adminpanel')h=adminPanel();
if(tab==='tasks')h='<div class="card"><div class="row between"><h3>준비·시연</h3>'+(admin?'<button class="admin" onclick="addTask()">+ 준비·시연 추가</button>':'')+'</div>'+S.tasks.map((t,i)=>'<div class="item row between '+(t.done?'taskdone':'')+'"><div><b>'+(t.done?'✓ ':'○ ')+esc(t.title)+'</b><div class="muted">담당자 '+esc(t.owner||'미정')+' · 마감 '+esc(t.due||'미정')+'</div><div>'+esc(t.note||'')+'</div></div>'+(admin?'<div class="row"><button class="edit" onclick="editTask('+i+')">수정</button><button class="edit" onclick="deleteTask('+i+')">삭제</button></div>':'')+'</div>').join('')+'</div>';
document.querySelector('#view').innerHTML=h}
async function api(action,data){let r;try{r=await fetch(SB+'/functions/v1/bixpo-admin',{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({action,password:adminPass,data})})}catch(e){let x=new Error('network');x.kind='network';throw x}let body={};try{body=await r.json()}catch(e){}if(r.status===401||r.status===403){let x=new Error('auth');x.kind='auth';throw x}if(!r.ok){let x=new Error(body.detail||body.error||('HTTP '+r.status));x.kind='db';x.status=r.status;throw x}return body}
async function adminLogin(){if(admin){admin=false;adminPass='';adminBtn.textContent='관리자 로그인';render();return}let p=prompt('관리자 비밀번호를 입력하세요.');if(!p)return;adminPass=p;try{await api('login');admin=true;adminBtn.textContent='관리자 로그아웃';render()}catch(e){adminPass='';if(e.kind==='network')alert('네트워크 오류입니다. 인터넷 연결을 확인한 뒤 다시 시도해 주세요.');else if(e.kind==='auth')alert('로그인 오류입니다. 관리자 비밀번호를 확인해 주세요.');else alert('관리자 로그인 서버 오류입니다. 잠시 후 다시 시도해 주세요.')}}
async function persist(){try{await api('save',S);await load();alert('저장했습니다. 모든 직원에게 공유됩니다.');return true}catch(e){if(e.kind==='auth'){admin=false;adminPass='';adminBtn.textContent='관리자 로그인';render();alert('로그인 오류입니다. 관리자 인증이 만료되었거나 비밀번호가 일치하지 않습니다. 다시 로그인해 주세요.')}else if(e.kind==='network')alert('네트워크 오류입니다. 인터넷 연결을 확인한 뒤 다시 저장해 주세요.');else alert('DB 저장 오류입니다. 공유 데이터베이스에 저장하지 못했습니다. 잠시 후 다시 시도해 주세요.');return false}}
function editPerson(i){let p=S.people[i],name=prompt('이름',p.name);if(name===null)return;p.name=name;p.role=prompt('역할',p.role)??p.role;p.down=prompt('출발 일정',p.down)??p.down;p.stay=prompt('숙박 일정',p.stay)??p.stay;p.up=prompt('복귀 일정',p.up)??p.up;p.note=prompt('메모',p.note)??p.note;persist()}
function addPerson(){let name=prompt('이름');if(!name)return;S.people.push({id:'p'+Date.now(),name,role:prompt('역할','전시안내')||'',down:prompt('출발 일정','미정')||'미정',stay:prompt('숙박 일정','미정')||'미정',up:prompt('복귀 일정','미정')||'미정',note:''});persist()}
function editShift(i){let s=S.shifts[i];s.people=prompt('근무자',s.people)??s.people;s.time=prompt('근무시간',s.time)??s.time;s.note=prompt('메모',s.note)??s.note;persist()}
function addTask(){let title=prompt('준비·시연 항목을 입력하세요.');if(!title)return;let owner=prompt('담당자를 입력하세요.','미정');if(owner===null)return;let due=prompt('마감일을 입력하세요.','11/3(화)');if(due===null)return;let note=prompt('메모를 입력하세요.','')??'';S.tasks.push({id:'t'+Date.now(),title,owner:owner||'미정',due:due||'미정',note,done:false});persist()}
function editTask(i){let t=S.tasks[i];let title=prompt('준비·시연 항목',t.title);if(title===null)return;let owner=prompt('담당자',t.owner||'미정');if(owner===null)return;let due=prompt('마감일',t.due||'미정');if(due===null)return;let note=prompt('메모',t.note||'');if(note===null)return;let done=confirm('완료된 항목이면 확인을 누르세요.\n취소를 누르면 미완료로 표시됩니다.');Object.assign(t,{title,owner:owner||'미정',due:due||'미정',note,done});persist()}
function deleteTask(i){let t=S.tasks[i];if(!confirm('「'+t.title+'」 항목을 삭제할까요?'))return;S.tasks.splice(i,1);persist()}
let deferredInstall=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});
window.addEventListener('appinstalled',()=>{if(installBtn)installBtn.textContent='✓ 앱 설치됨'});
function standalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
async function installPWA(){if(standalone()){alert('이미 홈 화면 앱으로 실행 중입니다.');return}if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;return}let ios=/iPhone|iPad|iPod/.test(navigator.userAgent);if(ios)alert('iPhone/iPad: 공유 버튼(□↑) → 홈 화면에 추가 → 추가한 BIXPO T/F 앱을 실행하세요.\n홈 화면 앱에서 푸시 알림을 받을 수 있습니다.');else alert('브라우저 메뉴에서 “앱 설치” 또는 “홈 화면에 추가”를 선택해 주세요.')}
function b64(s){let p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(b),a=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a}
async function pushApi(body){let r;try{r=await fetch(SB+'/functions/v1/bixpo-push',{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify(body)})}catch(e){let x=new Error('network');x.kind='network';throw x}let j={};try{j=await r.json()}catch(_){}if(r.status===401||r.status===403){let x=new Error('auth');x.kind='auth';throw x}if(!r.ok){let x=new Error(j.error||'push');x.kind='push';throw x}return j}
async function syncStaffPushSubscription(){if(!staffToken||!('serviceWorker'in navigator)||!('PushManager'in window))return;try{let reg=await navigator.serviceWorker.ready,sub=await reg.pushManager.getSubscription();if(!sub)return;chatPushRegistered=true;await pushApi({action:'subscribe',subscription:sub.toJSON(),token:staffToken})}catch(e){console.warn('Push device association failed',e)}}
async function enablePush(){try{if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window)){alert('이 기기/브라우저는 Web Push 알림을 지원하지 않습니다.');return}let ios=/iPhone|iPad|iPod/.test(navigator.userAgent);if(ios&&!standalone()){alert('iPhone/iPad에서는 먼저 이 앱을 홈 화면에 추가한 뒤, 홈 화면의 BIXPO T/F 앱을 열어 🔔 알림 받기를 눌러주세요.');return}let perm=await Notification.requestPermission();if(perm!=='granted'){alert('알림 권한이 허용되지 않았습니다. 기기 설정에서 알림을 허용해 주세요.');return}let reg=await navigator.serviceWorker.ready,key=await pushApi({action:'key'}),sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(key.publicKey)});await pushApi({action:'subscribe',subscription:sub.toJSON(),token:staffToken||undefined});chatPushRegistered=true;pushBtn.textContent='🔔 알림 등록됨';alert('푸시 알림 등록이 완료되었습니다. 앱을 닫아도 새 공지와 채팅 알림을 받을 수 있습니다.')}catch(e){alert(e.kind==='network'?'네트워크 오류로 알림 등록에 실패했습니다.':'푸시 알림 등록에 실패했습니다. 잠시 후 다시 시도해 주세요.')}}
const CHAT_POLL_MS=5000,STATE_POLL_MS=15000;
loadFAQ();restoreStaff();setInterval(loadChat,CHAT_POLL_MS);
if('serviceWorker'in navigator){navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.type==='bixpo_chat_push'&&e.data.chat)notifyChat(e.data.chat)});navigator.serviceWorker.register('/sw.js').then(async()=>{try{let r=await navigator.serviceWorker.ready,s=await r.pushManager.getSubscription();chatPushRegistered=!!s;if(s&&pushBtn)pushBtn.textContent='🔔 알림 등록됨'}catch(_){}})}
async function load(){let before=[...(S.notes||[])],oldState=JSON.stringify(S);try{let r=await fetch(SB+'/rest/v1/bixpo_state?id=eq.main&select=data,updated_at',{headers:{apikey:KEY,Authorization:'Bearer '+KEY},cache:'no-store'});if(!r.ok)throw 0;let j=await r.json();if(j[0])S=j[0].data}catch(e){try{let r=await fetch('data.json?v='+Date.now(),{cache:'no-store'});S=await r.json()}catch(_){}}let changed=oldState!==JSON.stringify(S);if(tab==='chat'){if(!document.querySelector('#view').innerHTML)render();else{renderNotice();renderHotel()}}else if(changed||!document.querySelector('#view').innerHTML)render();if(before.length)checkNewNotices(before)}load();setInterval(load,STATE_POLL_MS);
